server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  error:
    include-message: never
    include-binding-errors: never
    include-exception: false
    include-stacktrace: never
    whitelabel:
      enabled: false
    path: /error
  tomcat:
    basedir: my-tomcat
    accesslog:
      enabled: true
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  datasource:
    url: jdbc:postgresql://localhost:6432/shop
    username: postgres
    password: syboo782
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    check-template-location: true
    cache: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  web:
    resources:
      add-mappings: false
mybatis:
  mapper-locations: mybatis/**/*.xml
  type-aliases-package: com.syboo.shopping
  configuration:
    map-underscore-to-camel-case: true
logging:
  # 로그 레벨 설정
  level:
    root: info
    org:
      hibernate:
        type:
          descriptor:
            sql: trace